don't throw unhandled Exception if audio message is unplayable
When it is not possible to find the audio message to play, don't just crash
on a pointless, unhandled Exception. Instead put the error in a Toast, for
now.  I'm sure this can be presented to the user much better, but this at
least stops the crashes.

closes #4172 https://dev.guardianproject.info/issues/4172

here's the stacktrace:

java.lang.RuntimeException: Unable to start activity ComponentInfo{info.guardianproject.otr.app.im/info.guardianproject.otr.app.im.ui.AudioPlayerActivity}: java.lang.RuntimeException: java.io.IOException: File not found /2/download/Voice+102.3ga
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.RuntimeException: java.io.IOException: File not found /2/download/Voice+102.3ga
at info.guardianproject.otr.app.im.ui.AudioPlayerActivity.play(AudioPlayerActivity.java:96)
at info.guardianproject.otr.app.im.ui.AudioPlayerActivity.onCreate(AudioPlayerActivity.java:53)
at android.app.Activity.performCreate(Activity.java:5933)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
... 10 more
Caused by: java.io.IOException: File not found /2/download/Voice+102.3ga
at info.guardianproject.util.HttpMediaStreamer.create(HttpMediaStreamer.java:50)
at info.guardianproject.util.HttpMediaStreamer.<init>(HttpMediaStreamer.java:30)
at info.guardianproject.otr.app.im.ui.AudioPlayerActivity.initPlayer(AudioPlayerActivity.java:140)
at info.guardianproject.otr.app.im.ui.AudioPlayerActivity.play(AudioPlayerActivity.java:93)
... 14 more