fix NPE crash when setting background
It seems that not all devices can handle it:

java.lang.RuntimeException: Unable to start activity ComponentInfo{info.guardianproject.otr.app.im/info.guardianproject.otr.app.im.app.WelcomeActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
	at android.app.ActivityThread.access$600(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5416)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at info.guardianproject.otr.app.im.app.ThemeableActivity.setBackgroundImage(ThemeableActivity.java:79)
	at info.guardianproject.otr.app.im.app.ThemeableActivity.onCreate(ThemeableActivity.java:31)
	at info.guardianproject.otr.app.im.app.WelcomeActivity.onCreate(WelcomeActivity.java:91)
	at android.app.Activity.performCreate(Activity.java:5276)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1152)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
	... 11 more